// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// A a
// swagger:model A
type A struct {

	// f1
	F1 string `json:"f1,omitempty"`

	// f2
	F2 string `json:"f2,omitempty"`
}

// Validate validates this a
func (m *A) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *A) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *A) UnmarshalBinary(b []byte) error {
	var res A
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
