package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/yan-zhuang/swagger-allof-test/models"
)

/*GetAllofOK test

swagger:response getAllofOK
*/
type GetAllofOK struct {

	/*
	  In: Body
	*/
	Payload *models.B `json:"body,omitempty"`
}

// NewGetAllofOK creates GetAllofOK with default headers values
func NewGetAllofOK() *GetAllofOK {
	return &GetAllofOK{}
}

// WithPayload adds the payload to the get allof o k response
func (o *GetAllofOK) WithPayload(payload *models.B) *GetAllofOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get allof o k response
func (o *GetAllofOK) SetPayload(payload *models.B) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetAllofOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
