package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
)

// A a
// swagger:model A
type A struct {

	// f1
	F1 string `json:"f1,omitempty"`

	// f2
	F2 string `json:"f2,omitempty"`
}

// Validate validates this a
func (m *A) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
